### ISSUE TITLE
Political Profile Categories do not perform as expected

### ISSUE THREAD

**Issue by rdrapeau** [aaronnech/CheckYourBias#18] opened 2016-02-18 22:16 UTC
Navigate to the political profile section and notice how the default category is Crime and Safety. I can't seem to be able to consistently find the category of the data that is being displayed (1 time it was in environment, the other it was in economy). I think something is going on here.

**Comment by g-liu** [comment] 2016-03-01 22:13
Duplicate of #17? If so, closing.

**Closed as completed by g-liu** 2016-03-01 22:13 UTC
Labels: duplicate
