### ISSUE TITLE
Categories dropdown not restocking

### ISSUE THREAD

**Issue by rhwilk** [aaronnech/CheckYourBias#64] opened 2016-03-07 06:00 UTC
After submitting several issues, I noticed that some of the categories are disappearing from the dropdown list (only six are available now). I would guess this is an unintended side effect of removing already-chosen categories from the list - it looks like they aren't getting added back in properly when changing to a new issue.

**Comment by g-liu** [comment] 2016-03-07 21:14
To reproduce this bug:
1. Log in to app
2. Go to "Submit Content"
3. Fill out all required fields. Select 1 or more categories from the dropdown
4. Tap "Submit"
5. Notice that the category/categories selected in the previous submission are now missing from the categories dropdown.

(Please go into the database and delete the submission once you are done reproducing the bug!!)

This may be a "simple" matter of resetting a state variable in the submit component.

**Comment by rhwilk** [comment] 2016-03-07 23:48
While adding author handling, I added a line so that the categoriesList is regrabbed from the cache when the state is being reset for a new issue. This seems to fix the problem, but there might be a more elegant way to do it?

**Comment by g-liu** [comment] 2016-03-08 00:28
Sounds good to me. If you can verify that the issue is fixed, feel free to close the issue.

**Closed as completed** 2016-03-08 00:32 UTC
Labels: bug
